/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.example.btlappchamsocsuckhoe.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType User.
 *
 * @since 2021-11-24
 */
@PrimaryKeys({"id"})
public final class User extends CloudDBZoneObject {
    private String id;

    private String ten;

    private String gioitinh;

    private String huyetap;

    private String nhiptim;

    private String anhbia_url;

    private String avata_url;

    private String qrcode_url;

    private String tuoi;

    private String nhietdo;

    private String cannang;

    private String chieucao;

    private String tinhtrang;

    public User() {
        super(User.class);
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setTen(String ten) {
        this.ten = ten;
    }

    public String getTen() {
        return ten;
    }

    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }

    public String getGioitinh() {
        return gioitinh;
    }

    public void setHuyetap(String huyetap) {
        this.huyetap = huyetap;
    }

    public String getHuyetap() {
        return huyetap;
    }

    public void setNhiptim(String nhiptim) {
        this.nhiptim = nhiptim;
    }

    public String getNhiptim() {
        return nhiptim;
    }

    public void setAnhbia_url(String anhbia_url) {
        this.anhbia_url = anhbia_url;
    }

    public String getAnhbia_url() {
        return anhbia_url;
    }

    public void setAvata_url(String avata_url) {
        this.avata_url = avata_url;
    }

    public String getAvata_url() {
        return avata_url;
    }

    public void setQrcode_url(String qrcode_url) {
        this.qrcode_url = qrcode_url;
    }

    public String getQrcode_url() {
        return qrcode_url;
    }

    public void setTuoi(String tuoi) {
        this.tuoi = tuoi;
    }

    public String getTuoi() {
        return tuoi;
    }

    public void setNhietdo(String nhietdo) {
        this.nhietdo = nhietdo;
    }

    public String getNhietdo() {
        return nhietdo;
    }

    public void setCannang(String cannang) {
        this.cannang = cannang;
    }

    public String getCannang() {
        return cannang;
    }

    public void setChieucao(String chieucao) {
        this.chieucao = chieucao;
    }

    public String getChieucao() {
        return chieucao;
    }

    public void setTinhtrang(String tinhtrang) {
        this.tinhtrang = tinhtrang;
    }

    public String getTinhtrang() {
        return tinhtrang;
    }

}
