/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.example.btlappchamsocsuckhoe.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType yeucau.
 *
 * @since 2021-11-24
 */
@PrimaryKeys({"id_nguoi_gui", "id_nguoi_nhan"})
public final class yeucau extends CloudDBZoneObject {
    private String id_nguoi_gui;

    private String id_nguoi_nhan;

    public yeucau() {
        super(yeucau.class);
    }

    public void setId_nguoi_gui(String id_nguoi_gui) {
        this.id_nguoi_gui = id_nguoi_gui;
    }

    public String getId_nguoi_gui() {
        return id_nguoi_gui;
    }

    public void setId_nguoi_nhan(String id_nguoi_nhan) {
        this.id_nguoi_nhan = id_nguoi_nhan;
    }

    public String getId_nguoi_nhan() {
        return id_nguoi_nhan;
    }

}
